# Generated by Django 2.1.4 on 2019-01-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20190102_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='slug',
            field=models.SlugField(default='Main', max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.TextField(default='New Note', max_length=1024),
        ),
    ]
